import {LF} from "./lib_char.js"
import * as lib_datetime from "./lib_datetime.js"
import type {LlmConfig} from "./lib_llm_config.js"
import {PROGRAM_NAME, PROGRAM_VERSION} from "./lib_package_details.js"

export default {}

export function add_footer({llm_response, llm_config}: {llm_response: string; llm_config: LlmConfig}): string {
  const {llm_model_name} = llm_config

  const timestamp = lib_datetime.format_local_iso_ymd_hms(new Date())

  const footer = `Generated by: ${PROGRAM_NAME} v${PROGRAM_VERSION} at ${timestamp} using ${llm_model_name}`

  return llm_response.trim() + LF + LF + footer
}
