import {LF} from "./lib_char_control.js"
import {EMPTY} from "./lib_char_empty.js"
import {datetime_format_local_iso_ymd_hms} from "./lib_datetime.js"
import type {LlmConfig} from "./lib_llm_config.js"
import {PACKAGE_NAME, PACKAGE_VERSION} from "./lib_package.js"

export function diffdash_add_prefix_or_suffix({
  git_message,
  add_prefix,
  add_suffix,
}: {git_message: string; add_prefix: string | undefined; add_suffix: string | undefined}): string {
  if (!add_prefix && !add_suffix) {
    return git_message
  }

  const lines = git_message.split(LF)
  if (lines.length === 0) {
    return git_message
  }

  const formatted_prefix = add_prefix ? `${add_prefix} ` : EMPTY
  const formatted_suffix = add_suffix ? ` ${add_suffix}` : EMPTY

  lines[0] = `${formatted_prefix}${lines[0]}${formatted_suffix}`

  return lines.join(LF)
}

export function diffdash_add_footer({git_message, llm_config}: {git_message: string; llm_config: LlmConfig}): string {
  const {llm_model_name} = llm_config

  const timestamp = datetime_format_local_iso_ymd_hms(new Date())

  const footer = `Generated by: ${PACKAGE_NAME} v${PACKAGE_VERSION} at ${timestamp} using ${llm_model_name}`

  return git_message.trim() + LF + LF + footer
}
