import * as lib_abort from "./lib_abort.js"
import {EMPTY} from "./lib_char.js"
import * as lib_datetime from "./lib_datetime.js"
import * as lib_debug from "./lib_debug.js"
import * as lib_git_message_prompt from "./lib_git_message_prompt.js"
import * as lib_git_message_validate from "./lib_git_message_validate.js"
import * as lib_llm_chat from "./lib_llm_chat.js"
import type {LlmConfig} from "./lib_llm_config.js"
import * as lib_llm_config from "./lib_llm_config.js"
import * as lib_package_details from "./lib_package_details.js"
import * as lib_tell from "./lib_tell.js"

export default {}

export interface GitMessageGenerateDetails {
  llm_config: LlmConfig
  diffstat: string
  diff: string
}

/**
 * Add a footer to a commit message
 */
function add_footer(message: string, model: string): string {
  const timestamp = lib_datetime.format_local_iso_ymd_hms(new Date())
  const footer = `\n\nGenerated by: ${lib_package_details.PROGRAM_NAME} v${lib_package_details.PROGRAM_VERSION} at ${timestamp} using ${model}`

  // Ensure there's proper spacing before the footer
  const trimmed_message = message.trim()
  return trimmed_message + footer
}

/**
 * Generate a commit message for staged changes
 */
export async function generate_message(details: GitMessageGenerateDetails): Promise<string> {
  const {llm_config, diffstat, diff} = details

  const {llm_model} = llm_config

  lib_llm_config.show_llm_config({llm_config, verbose: true})

  // Create the system prompts
  const system_prompt = lib_git_message_prompt.get_system_prompt()

  // Create the user prompt
  const user_prompt = lib_git_message_prompt.get_user_prompt({
    diffstat,
    diff,
    original: EMPTY,
    use_original: false,
  })

  // Call the LLM API to generate a message
  const llm_response = await lib_llm_chat.call_llm({llm_config, system_prompt, user_prompt})

  if (!llm_response.success) {
    lib_abort.abort(`LLM API call failed: ${llm_response.error_message}`)
  }

  // Validate the generated message
  const validation_result = lib_git_message_validate.validate_message(llm_response.text)

  if (!validation_result.valid) {
    lib_tell.warning(`Generated message failed validation: ${validation_result.reason}`)

    if (validation_result.suggested_fix) {
      lib_tell.info("Using suggested fix")
      return add_footer(validation_result.suggested_fix, llm_model)
    }

    // If no fix is suggested, abort
    lib_abort.abort("Unable to use the generated message")
  }

  // Add a footer to the generated message
  return add_footer(llm_response.text, llm_model)
}
