import {EMPTY, LF} from "./lib_char.js"
import * as lib_datetime from "./lib_datetime.js"
import type {LlmConfig} from "./lib_llm_config.js"
import {PROGRAM_NAME, PROGRAM_VERSION} from "./lib_package_details.js"

export default {}

export function add_prefix_or_suffix({
  message,
  add_prefix,
  add_suffix,
}: {message: string; add_prefix: string | undefined; add_suffix: string | undefined}): string {
  if (!add_prefix && !add_suffix) {
    return message
  }

  const lines = message.split(LF)
  if (lines.length === 0) {
    return message
  }

  const formatted_prefix = add_prefix ? `${add_prefix} ` : EMPTY
  const formatted_suffix = add_suffix ? ` ${add_suffix}` : EMPTY

  lines[0] = `${formatted_prefix}${lines[0]}${formatted_suffix}`

  return lines.join(LF)
}

export function add_footer({message, llm_config}: {message: string; llm_config: LlmConfig}): string {
  const {llm_model_name} = llm_config

  const timestamp = lib_datetime.format_local_iso_ymd_hms(new Date())

  const footer = `Generated by: ${PROGRAM_NAME} v${PROGRAM_VERSION} at ${timestamp} using ${llm_model_name}`

  return message.trim() + LF + LF + footer
}
