export default {}

export const EMPTY = ""

export const BS = "\b"
export const CR = "\r"
export const ESC = "\u001B"
export const FF = "\f"
export const LF = "\n"
export const NUL = "\0"
export const SP = " "
export const TAB = "\t"
export const VT = "\v"

export const AMPERSAND = "&"
export const APOSTROPHE = "'"
export const ASTERISK = "*"
export const AT = "@"
export const BACKSLASH = "\\"
export const BACKTICK = "`"
export const CARET = "^"
export const COLON = ":"
export const COMMA = ","
export const CURLY_LEFT = "{"
export const CURLY_RIGHT = "}"
export const DASH = "-"
export const DOLLAR = "$"
export const DOT = "."
export const ELLIPSIS = "…"
export const EQUALS = "="
export const HASH = "#"
export const HAT = "^"
export const LESS_THAN = "<"
export const MORE_THAN = ">"
export const MINUS = "-"
export const PERCENT = "%"
export const PIPE = "|"
export const PLUS = "+"
export const POUND_SIGN = "£"
export const QUESTION = "?"
export const QUOTE_DOUBLE = '"'
export const QUOTE_SINGLE = "'"
export const ROUND_LEFT = "("
export const ROUND_RIGHT = ")"
export const SEMICOLON = ";"
export const SLASH = "/"
export const SPACE = " "
export const SQUARE_LEFT = "["
export const SQUARE_RIGHT = "]"
export const TILDE = "~"
export const UNDERSCORE = "_"

export const DIGIT_0 = "0"
export const DIGIT_1 = "1"
export const DIGIT_2 = "2"
export const DIGIT_3 = "3"
export const DIGIT_4 = "4"
export const DIGIT_5 = "5"
export const DIGIT_6 = "6"
export const DIGIT_7 = "7"
export const DIGIT_8 = "8"
export const DIGIT_9 = "9"

export const LEFT_DOUBLE_QUOTATION_MARK = "“"
export const LEFT_SINGLE_QUOTATION_MARK = "‘"
export const RIGHT_DOUBLE_QUOTATION_MARK = "”"
export const RIGHT_SINGLE_QUOTATION_MARK = "’"

export const BOX_DRAWINGS_HEAVY_HORIZONTAL = "\u2501"
